services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"
  api1: &api
    build: .
    hostname: rinha-api1
    environment:
      - APP_PORT=8080
      - POSTGRES_URL=postgres://user:password@postgres:5432/dbname
      - DEFAULT_PROCESSOR_URL=http://host.docker.internal:8001
      - FALLBACK_PROCESSOR_URL=http://host.docker.internal:8002
      - GOGC=100
      - GOMAXPROCS=1
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
  api2:
    <<: *api
    hostname: rinha-api2
    environment:
      - APP_PORT=8080
      - POSTGRES_URL=postgres://user:password@postgres:5432/dbname
      - DEFAULT_PROCESSOR_URL=http://host.docker.internal:8001
      - FALLBACK_PROCESSOR_URL=http://host.docker.internal:8002
      - GOGC=100
      - GOMAXPROCS=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=dbname
    command: postgres -c max_connections=450 -c shared_buffers=32MB -c effective_cache_size=96MB -c work_mem=3MB -c maintenance_work_mem=12MB -c synchronous_commit=off -c fsync=off
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"

networks:
  backend:
    driver: bridge
