services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
  api1: &api
    image: mateusgms/rinha-2025-go:latest
    hostname: rinha-api1
    environment:
      - APP_PORT=8080
      - POSTGRES_URL=postgres://user:password@postgres:5432/dbname
    networks:
      - backend
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"
  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8081
      - POSTGRES_URL=postgres://user:password@postgres:5432/dbname

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    command: postgres -c max_connections=450 -c shared_buffers=32MB -c effective_cache_size=96MB -c work_mem=3MB -c maintenance_work_mem=12MB -c synchronous_commit=off -c fsync=off
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "110MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true