services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"
  api1: &api
    image: mateusgms/rinha-2025-go:latest
    hostname: rinha-api1
    environment:
      - APP_PORT=8080
      - POSTGRES_URL=postgres://user:password@postgres:5432/dbname?sslmode=disable
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "70MB"
  api2:
    <<: *api
    hostname: rinha-api2
    environment:
      - APP_PORT=8080
      - POSTGRES_URL=postgres://user:password@postgres:5432/dbname?sslmode=disable
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=dbname
    command: postgres -c max_connections=250 -c shared_buffers=120MB -c effective_cache_size=300MB -c work_mem=4MB -c maintenance_work_mem=40MB -c synchronous_commit=off -c fsync=off -c wal_buffers=16MB -c checkpoint_completion_target=0.9 -c random_page_cost=1.1 -c log_statement=none -c log_duration=off -c autovacuum=off -c full_page_writes=off -c ssl=off -c effective_io_concurrency=300 -c min_wal_size=2GB -c max_wal_size=8GB -c commit_delay=10 -c commit_siblings=5
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
